### ISSUE TITLE
Name brainstorming for whole project

### ISSUE THREAD

**Issue by cwgoes** [heliaxdev/typhon#26]
Heterogenous Paxos is the name of the algorithm, and Chimera chains are the name of the particular feature, but we need a name for the whole project, including consensus algorithm design, proof-of-stake integration, Rust implementation, etc. Please comment with nominated name ideas and we can collectively decide in a week or so.

**Comment by isheff** [comment]
Project Typhon
(In Greek mythology, Typhon is the Chimera's father)

**Comment by isheff** [comment]
HetCons
(Heterogeneous Consensus)

**Comment by cwgoes** [comment]
> Project Typhon

Haha, I like it, only potential name conflict is [this](https://github.com/pandoracore/typhon-spec/blob/master/README.md) but probably OK (looks abandoned)

**Comment by cwgoes** [comment]
Settled on "Typhon". :tada:
