### ISSUE TITLE
Prove Heterogeneous Paxos Agreement in IVY or TLA+

### ISSUE THREAD

**Issue by isheff** [heliaxdev/typhon#3]
Using the [Heterogeneous Paxos](https://arxiv.org/abs/2011.08253) [Spec developed earlier](https://github.com/heliaxdev/hpaxos/issues/2), formalize and prove heterogeneous agreement in [Ivy](http://microsoft.github.io/ivy/) or [TLA+](https://lamport.azurewebsites.net/tla/tla.html).

We should also prove non-triviality, but that should be very easy.

**Comment by isheff** [comment]
@karbyshev has proven agreement (safety) for a version of Heterogeneous Paxos in IVY, but without the FOL -> EPR equivalence. We have now moved to trying to prove safety for an equivalent version in TLA+.

**Comment by karbyshev** [comment]
TLA+ [proof of agreement](https://github.com/heliaxdev/typhon/blob/master/tla/HPaxos.tla) is complete for a version of Heterogeneous Paxos.
