### ISSUE TITLE
Start written specification for heterogenous Paxos Tendermint-flavoured

### ISSUE THREAD

**Issue by cwgoes** [heliaxdev/typhon#5]
[Specification document HackMD](https://hackmd.io/@heliax/B1r61iSSK)

Prior discussions:
- [Old HackMD notes](https://hackmd.io/@heliax/H1ZUkpg2O)
- [Old notes](https://github.com/heliaxdev/dist-sys-research/tree/master/heterogeneous-paxos)
- [Meeting agendas](https://hackmd.io/04rwo1M5TF6TWFT_HHyXWw?both)

**Comment by isheff** [comment]
[This specification is indeed started](https://spec.anoma.network/master/architecture/a1/typhon.html). More details, however, [can still be fleshed out](https://github.com/heliaxdev/typhon/issues/32)
